/* Practice mode catalogue. Each maps to a REAL backend scenario. */
const MODES = {
  communication: { title: "Communication", ic: "◐", scenario: "conversation",
    desc: "Clear, confident everyday speaking.", purpose: "Build clarity, confidence and natural flow.",
    focuses: ["General Conversation", "Clear Speaking", "Confidence", "Spontaneous Communication", "Interview Communication", "Camera Presence"] },
  story: { title: "Storytelling Studio", ic: "✎", scenario: "story",
    desc: "Hooks, stakes and memorable endings.", purpose: "Turn experiences into stories people remember.",
    kinds: ["Personal Story", "Interview Story", "Professional Story", "Short Story", "Random Prompt"],
    prompts: ["Tell me about a time you failed and what it taught you.", "Describe a moment that changed how you work.",
      "Tell me about the hardest problem you ever solved.", "Share a story about helping someone under pressure.",
      "Narrate a day that did not go as planned."] },
  speaking: { title: "Public Speaking", ic: "▤", scenario: "presentation",
    desc: "Stage presence and structured delivery.", purpose: "Own the room: openings, transitions, closings.",
    kinds: ["Presentation", "Stage Simulation", "Persuasive Speech", "Topic Explanation", "Impromptu Speech"] },
  wit: { title: "Wit & Engagement", ic: "✦", scenario: "wit",
    desc: "Natural humor and clever framing.", purpose: "Be memorable without forcing jokes.",
    prompts: ["Convince me Mondays are underrated.", "Pitch your hometown like a movie trailer.",
      "Explain your job as if it were a sport.", "Defend an unpopular opinion, playfully."] },
  qa: { title: "Spontaneous Q&A", ic: "⚡", scenario: "spontaneous",
    desc: "Think fast, answer sharp.", purpose: "Structure under pressure: 10 seconds to think, then speak.",
    prompts: ["Explain AI to a 10-year-old.", "Why should I care about your project?", "You have 20 seconds: convince me.",
      "Explain your work without technical words.", "What went wrong, and what did you learn?", "Teach me something in 30 seconds."] },
  podcast: { title: "Podcast Studio", ic: "◍", scenario: "podcast",
    desc: "Record a segment, review the take.", purpose: "Conversational energy, hooks and listener focus.",
    kinds: ["Solo Segment", "Interview Format", "Explainer", "Opinion Take"] },
  conversation: { title: "General Conversation", ic: "◉", scenario: "conversation",
    desc: "Free-form talk with light coaching.", purpose: "Stay natural, clear and engaging." },
};
